### ISSUE TITLE
Support repositories using Cgit web frontend.

### ISSUE THREAD

**Issue by ahakanbaba** [ruanyl/vim-gh-line#15]
[Cgit](https://git.zx2c4.com/cgit/about/) is a reasonably popular git repo front end. 
For example [gnu](http://git.savannah.gnu.org/cgit/) and [bash](http://git.savannah.gnu.org/cgit/bash.git/) source code use cgit. It is also  extensively used in several companies' internally hosted repositories.

It uses urls like this
```
http://git.savannah.gnu.org/cgit/bash.git/tree/lib/readline/savestring.c#n11
http://git.savannah.gnu.org/cgit/bash.git/tree//lib/readline/readline.c?id=36f89ff1d8b761c815d8993e9833e6357a57fc6b#n1060
http://git.savannah.gnu.org/cgit/bash.git/tree//lib/readline/readline.c?id=34dbca51a5fb5938db2e69ebb3318bbb182c2902#n1060
```

There may be various urls using the cgit front end. So we should also add a `g:gh_cgit_domain` variable. 

If the proposal is accepted, I am more than happy to work on the implementation, FYI.

**Comment by ruanyl** [comment]
@ahakanbaba PR is welcome :)

**Comment by ahakanbaba** [comment]
@ruanyl with merging #24 this issue is also fixed.
