### ISSUE TITLE
Add automated tests

### ISSUE THREAD

**Issue by ahakanbaba** [ruanyl/vim-gh-line#18]
The supported use-cases by this plugin are increasing very fast so that manually verifying all of them becomes impossible. Automated tests would be great and help with the development significantly. 

Some of the different dimensions to test: 
- Github, BitBucket,GitLab, hopefully [Cgit](https://github.com/ruanyl/vim-gh-line/issues/15)... 
- Different sed versions. 
- User configuration variables like g:(github|gitlab)_domain or gh_canonical .. 
- ...

I ran into some other vim plugins that execute automated tests. 

- [vim-go](https://github.com/fatih/vim-go) I think uses its own [setup](https://github.com/fatih/vim-go/blob/master/scripts/test#L72) for tests. 
- [vim-markdown](https://github.com/plasticboy/vim-markdown/tree/master/test) uses [vader](https://github.com/junegunn/vader.vim)
- [vim-puppet](https://github.com/rodjek/vim-puppet/tree/master/test/format) also uses vader. 

Something similar can be explored here too.

**Comment by ahakanbaba** [comment]
@KostyaEsmukov  you mentioned a need to automated tests in your [comment](https://github.com/ruanyl/vim-gh-line/pull/17#issuecomment-435654639). I created this issue for that. FYI.

**Comment by KostyaEsmukov** [comment]
@ahakanbaba Thanks!

Given that this project relies on sed, which is not quite portable getween GNU and BSD, I think it would be great to run the automated tests in both Linux and *BSD. Unfortunately, I'm not aware of any service like Travis CI which provide support for running jobs on *BSD.

Another option is to replace sed with something more portable so it could be enough to run tests just on Linux.

**Comment by ahakanbaba** [comment]
Both [CircleCI](https://circleci.com/build-environments/xcode/osx/) and [Travis](https://docs.travis-ci.com/user/reference/osx/) support running on OSX. I think the default sed in OSX is not the GNU sed.

**Comment by KostyaEsmukov** [comment]
Oh, I didn't think of OSX. Yeah, that should do it: `sed` in macOS is indeed the BSD's one.

**Comment by ahakanbaba** [comment]
While working on Cgit support (#15) I really felt the need to write unit-tests. The different use-cases really explode in number. However testing the script-local functions in plugin/vim-gh-line.vim are not straight forward. Asked a question about it [here](https://vi.stackexchange.com/q/17866/13792). If anyone have suggestions I would appreciate.

**Comment by ahakanbaba** [comment]
@ruanyl This issue can also be closed. We have automated tests running in PR time.
