### ISSUE TITLE
E481: No range allowed for visual select

### ISSUE THREAD

**Issue by alinpopa** [ruanyl/vim-gh-line#29]
Hi,

I've noticed that after this commit https://github.com/ruanyl/vim-gh-line/commit/5c4a447bcbdea4cff4718e34974cab5f2beb7e23
I'm getting the `E481: No range allowed` when doing a visual select and then `<leader>gh`

If going back to the previous commit https://github.com/ruanyl/vim-gh-line/commit/529eba4d1369f3cf13426cac5f46ba76f512022d everything seems to be fine.
I wasn't able to pinpoint what's causing this, tho.

Thanks.

**Comment by ruanyl** [comment]
Thank you for reporting. Fixed now :)
