### ISSUE TITLE
Plugin only works if you install from your fork

### ISSUE THREAD

**Issue by timc1** [ruanyl/vim-gh-line#40]
Thank you for this awesome plugin! :)

Just dropping a note that I was only able to get this to work after forking the repo – since during `PluginInstall` we need to enter our Github credentials, we don't have access to this specific repository.

**Comment by ruanyl** [comment]
@timc1 what does the error message say? Since this is a public repo, people should be able to clone freely. Could it be the rate limit of GitHub public API access?

**Comment by timc1** [comment]
@ruanyl weird – I ran `PluginInstall` again with this repo today and it worked. Yesterday it required Github credentials 🤷🏻‍♂️

**Comment by ruanyl** [comment]
I guess that's probably Github rate limit, closed the issue now :)
