### ISSUE TITLE
Handle custom domain origins

### ISSUE THREAD

**Issue by gegoune** [ruanyl/vim-gh-line#45]
Is it possible to map origin domains that were mapped to those set up in ssh config with:

```
Host custom-domain
  Hostname     github.com
```
with origin being:

```
origin	git@custom-domain:user/repo.git (fetch)
```
Thanks.

**Comment by williamspatrick** [comment]
I did this ugly hack for mine:
```
let g:gh_open_command = 'fn() { echo "$@" | sed "s#ssh://openbmc.gerrit#https://github.com#" | xargs xdg-open }; fn '
```

**Comment by gegoune** [comment]
Ah, old issue. I have since written functions in to handle all my use cases. I am not using this plugin so will close it, if @ruanyl thinks it's worth keeping it open, feel free to reopen.

Thanks @williamspatrick though!
